#!/bin/bash

# LICENSE ######################################################################
# ##############################################################################
#
# Copyright 2017 Danny Wahl (danny@instructure.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# HELPER FUNCTIONS #############################################################
# ##############################################################################
cmd=${0##*/}
ver="1.0.0"
$(insthelp checkdeps) > /dev/null 2>&1
curlopts=$(insthelp curlopts)
outputrenderer=$(insthelp setrenderer)
httpmethod=$(insthelp sethttp)

# PREF FILE ####################################################################
# ##############################################################################
if [ -f ~/.inst ]; then
  . ~/.inst
  if [ -z $canvas_domain ] || [ -z $canvas_token ]; then
   $(insthelp setconfig $cmd)
   exit
  fi
else
 $(insthelp setconfig $cmd)
 exit
fi

# PARSE OPTS ###################################################################
# ##############################################################################
formopts=""
if [ $# -eq 0 ] && [ ! -f ~/.inst ]; then
  $(insthelp readconfig $cmd)
  $(insthelp help $cmd)
  exit 2
elif [ $# -eq 0 ] && [ -f ~/.inst ]; then
  $(insthelp help $cmd)
  exit 2
else
  while [ $# -gt 0 ] && [ "$1" != "--" ]; do
    while getopts ":hlvcsr:x:X:t:d:o:f:F:" opt; do
      case $opt in
        h)
          $(insthelp verbosehelp $cmd)
          exit ;;
        l)
          $(insthelp license)
          exit ;;
        v)
          $(insthelp version $cmd $ver)
          exit ;;
        c)
          $(insthelp setconfig $cmd)
          exit ;;
        s)
          sample=true ;;
        r)
          outputrenderer=$(insthelp setrenderer $OPTARG) ;;
        X|x)
          $(insthelp sethttp $OPTARG) ;;
        d)
          canvas_domain="$OPTARG" ;;
        t)
          canvas_token="$OPTARG" ;;
        o)
          outputpath=$(insthelp setoutput $OPTARG ${BASH_ARGV[0]})
          if [ "$outputpath" = "ERR" ]; then exit 1; fi ;;
        F|f)
          formopts="$formopts -F $OPTARG" ;;
        \?)
          printf >&2 "Invalid option: \`-$OPTARG\`\r\n"
          $(insthelp help $cmd)
          exit 2 ;;
        :)
          printf >&2 "Missing argument for \`-$OPTARG\`\r\n"
          $(insthelp help $cmd)
          exit 2 ;;
      esac
    done
    shift $((OPTIND-1))
    if [ $# -gt 0 ] && ! [[ "$1" =~ ^- ]]; then
      path="$1"
      shift
      break
    else
      printf >&2 "No API method provided\r\n"
      $(insthelp help $cmd)
      exit 2
    fi
  done
  if [ "$1" == "--" ]; then
    shift
    path=("${path[@]}" "$@")
  fi
fi

# BUILD COMMAND ################################################################
# ##############################################################################
if [ -z "$canvas_domain" ] && [ -z "$canvas_token" ]; then
  $(insthelp readconfig $cmd)
elif [ -z "$canvas_domain" ] || [ -z "$canvas_token" ]; then
  prinitf >&2 "Both \`-d\` and \`-t\` are requied when not using a config file"
  $(insthelp help $cmd)
  exit 2
fi

if [ -n "$outputpath" ] && [ -n "$outputrenderer" ]; then
  outputrenderer=""
fi

# START SESSION ################################################################
# ##############################################################################
JWT=$(curl $curlopts -H "Authorization: Bearer $canvas_token" -X GET "https://$canvas_domain.instructure.com/api/lti/accounts/self/jwt_token?tool_launch_url=https://lor.instructure.com/api/lti" | jq -r .jwt_token)
if [ $? -gt 0 ]; then
  printf >&2 "Unable to generate a JSON Web Token.  Please ensure that your credentials are accurate.\r\n"
  exit 2
fi
session=$(curl $curlopts -H "Content-Type: application/json" --data '{"jwt_token":"'$JWT'"}' -X POST "https://lor.instructure.com/api/sessions" | jq -r .sessionId)
if [ $? -gt 0 ]; then
  printf >&2 "Unable to generate a session.  Please ensure that your credentials are accurate.\r\n"
  exit 2
fi

# BUILD COMMAND ################################################################
# ##############################################################################
if [[ $path == *"/download" ]]; then
  if [ -z "$outputpath" ]; then
    printf >&2 "Downloading files requires an output path with \`-o\`\r\n"
    $(insthelp help $cmd)
    exit 2
  fi
  curlopts="$curlopts -L"
  outputrenderer=""
fi

command="curl $curlopts -H \"X-Session-ID: $session\" -X $httpmethod \"https://lor.instructure.com/api/$path\" $formopts $outputrenderer $outputpath"
if [ "$sample" = true ]; then
  printf >&2 "$command"
else
  eval $command
fi

# DELETE SESSION ###############################################################
# ##############################################################################
closesession="curl $curlopts -H \"X-Session-ID: $session\" \"https://lor.instructure.com/api/sessions/logout\""
eval $closesession
