#!/bin/bash

# LICENSE ######################################################################
# ##############################################################################
#
# Copyright 2017 Danny Wahl (danny@instructure.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# HELPER FUNCTIONS #############################################################
# ##############################################################################
cmd=${0##*/}
ver="1.2.0"
$(insthelp checkdeps) > /dev/null 2>&1
curlopts=$(insthelp curlopts)
outputrenderer=$(insthelp setrenderer)
httpmethod=$(insthelp sethttp)

# PREF FILE ####################################################################
# ##############################################################################
if [ -f ~/.inst ]; then
  . ~/.inst
  if [ -z $canvas_domain ] || [ -z $canvas_token ]; then
   $(insthelp setconfig $cmd)
   exit
  fi
else
 $(insthelp setconfig $cmd)
 exit
fi
cfg_domain=$canvas_domain

# PAGINATION ###################################################################
# ##############################################################################
pagecount=1
pageint=1
perpage=10

nextpage() {
  pageint=$((pageint+1))
  setpage $pageint
}

setpage() {
  local n=$1
  page=$n
}

setcount() {
  local n=$1
  if [ $n -gt 100 ]; then
    perpage=100
  else
    perpage=$n
  fi
}

makepage() {
  query=$(insthelp setquery $path)
  page="${query}page=${pageint}"
}

makeperpage() {
  query=$(insthelp setquery $path$page)
  perpage="${query}per_page=${perpage}"
}

getpages() {
  local command=$1
  shopt -s extglob
  while IFS=':' read key value; do
      value=${value##+([[:space:]])}; value=${value%%+([[:space:]])}
      case "$key" in
          Link) link="$value";;
       esac
  done < <(eval $command)
  IFS=',' read -r -a link <<< "$link"
  for index in "${!link[@]}"
  do
    if [[ ${link[index]} == *"last"* ]]; then
      link=${link[index]}
      break
    fi
  done
  link=${link##*\?}
  for val in ${link//&/ };do
    key=( ${val/=/ } )
    k=${key[0]}
    if [ $k == "page" ]; then
      pagecount=${key[1]}
    fi
  done
}

# PARSE OPTS ###################################################################
# ##############################################################################
formopts=""
if [ $# -eq 0 ] && [ ! -f ~/.inst ]; then
  $(insthelp readconfig $cmd)
  $(insthelp help $cmd)
  exit 2
elif [ $# -eq 0 ] && [ -f ~/.inst ]; then
  $(insthelp help $cmd)
  exit 2
else
  while [ $# -gt 0 ] && [ "$1" != "--" ]; do
    while getopts ":hlvcaszg:i:p:q:r:x:X:t:d:o:f:F:" opt; do
      case $opt in
        h|help)
          $(insthelp verbosehelp $cmd)
          exit ;;
        l|license)
          $(insthelp license)
          exit ;;
        v|version)
          $(insthelp version $cmd $ver)
          exit ;;
        c|config)
          $(insthelp setconfig $cmd)
          exit ;;
        a|all)
          getpages=true ;;
        s|sample)
          sample=true ;;
        g|graphql)
          graphql=true
          graphql_operation="$OPTARG" ;;
        z|quiz)
          quiz=true ;;
        i|info)
          graphql_variables="$OPTARG" ;;
        q|quantity)
          perpage="$OPTARG" ;;
        p|page)
          pageint="$OPTARG" ;;
        r|renderer)
          outputrenderer=$(insthelp setrenderer $OPTARG) ;;
        X|x)
          httpmethod=$(insthelp sethttp $OPTARG) ;;
        d|domain)
          canvas_domain="$OPTARG" ;;
        t|token)
          canvas_token="$OPTARG" ;;
        o|output)
          outputpath=$(insthelp setoutput $OPTARG ${BASH_ARGV[0]})
          if [ "$outputpath" = "ERR" ]; then exit 1; fi ;;
        F|f)
          formopts="$formopts -F $OPTARG" ;;
        \?)
          printf >&2 "Invalid option: \`-$OPTARG\`\r\n"
          $(insthelp help $cmd)
          exit 2 ;;
        :)
          printf >&2 "Missing argument for \`-$OPTARG\`\r\n"
          $(insthelp help $cmd)
          exit 2 ;;
      esac
    done
    shift $((OPTIND-1))
    if [ $# -gt 0 ] && ! [[ "$1" =~ ^- ]]; then
      path="$1"
      shift
      break
    else
      printf >&2 "No API method provided\r\n"
      $(insthelp help $cmd)
      exit 2
    fi
  done
  if [ "$1" == "--" ]; then
    shift
    path=("${path[@]}" "$@")
  fi
fi

# BUILD COMMAND ################################################################
# ##############################################################################
if [ -z "$canvas_domain" ] && [ -z "$canvas_token" ]; then
  $(insthelp readconfig $cmd)
elif [ -z "$canvas_domain" ] || [ -z "$canvas_token" ]; then
  printf >&2 "Both \`-d\` and \`-t\` are requied when not using a config file\r\n"
  $(insthelp help $cmd)
  exit 2
fi

if [ $canvas_domain = "beta" ] || [ $canvas_domain = "test" ]; then
  $(insthelp readconfig $cmd)
  canvas_domain="$cfg_domain.$canvas_domain"
fi

if [ -n "$outputpath" ] && [ -n "$outputrenderer" ]; then
  outputrenderer=""
fi

prefix=""
if [ "${path:0:5}" == "files" ] && [[ $path == *"download_frd=1"* ]]; then
  if [ -z "$outputpath" ]; then
    printf >&2 "Downloading files requires an output path with \`-o\`\r\n"
    $(insthelp help $cmd)
    exit 2
  fi
  curlopts="$curlopts -L"
  outputrenderer=""
else
  curlopts="$curlopts -H \"Authorization: Bearer $canvas_token\""
  if [ "$graphql" = true ]; then
    prefix="api/graphql"
  elif [ "$quiz" = true ]; then
    prefix="api/quiz/v1/"
  else
    prefix="api/v1/"
  fi
fi

if [ "$graphql" = true ]; then
  if [ "${path:0:6}" == "query " ]; then
    path=${path:6}
  elif [ "${path:0:9}" == "mutation " ]; then
    path=${path:9}
  elif [ "${path:0:13}" == "subscription " ]; then
    path=${path:13}
  fi
  if [ "$graphql_operation" != "query" ] && [ "$graphql_operation" != "mutation" ] && [ "$graphql_operation" != "subscription" ]; then
    graphql_operation="query"
  fi
  command="curl $curlopts -X POST \"https://$canvas_domain.instructure.com/$prefix\" -d query='$graphql_operation $path' -d '$graphql_variables' $outputrenderer $outputpath"
  if [ "$sample" = true ]; then
    printf >&2 "$command\r\n"
  else
    eval $command
  fi
else
  makepage
  makeperpage
  if [ "$getpages" = true ] && [ "$httpmethod" == "GET" ] && [ "$prefix" == "api/v1/" ]; then
    command="curl $curlopts -I -X $httpmethod \"https://$canvas_domain.instructure.com/$prefix$path$page$perpage\""
    getpages "$command"
  fi

  if [ $httpmethod != "GET" ]; then
    perpage=""
    page=""
    pagecount=1
  fi

  while
    command="curl $curlopts -X $httpmethod \"https://$canvas_domain.instructure.com/$prefix$path$page$perpage\" $formopts $outputrenderer $outputpath"
    if [ "$sample" = true ]; then
      printf >&2 "$command\r\n"
    else
      eval $command
    fi
    (( $pageint < $pagecount ))
  do
    nextpage
    continue
  done
fi
