#!/bin/bash

# LICENSE ######################################################################
# ##############################################################################
#
# Copyright 2017 Danny Wahl (danny@instructure.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# HELPER FUNCTIONS #############################################################
# ##############################################################################
cmd=${0##*/}
ver="1.0.0"
$(insthelp checkdeps) > /dev/null 2>&1
curlopts=$(insthelp curlopts)
outputrenderer=$(insthelp setrenderer)
httpmethod=$(insthelp sethttp)

# PREF FILE ####################################################################
# ##############################################################################

if [ -f ~/.inst ]; then
  . ~/.inst
  if [ -z $bridge_domain ] || [ -z $bridge_token ]; then
   $(insthelp setconfig $cmd)
   exit
  fi
else
 $(insthelp setconfig $cmd)
 exit
fi

# PARSE OPTS ###################################################################
# ##############################################################################

formopts=""
if [ $# -eq 0 ] && [ ! -f ~/.inst ]; then
  $(insthelp readconfig $cmd)
  $(insthelp help $cmd)
  exit 2
elif [ $# -eq 0 ] && [ -f ~/.inst ]; then
$(insthelp help $cmd)
exit 2
else
  while [ $# -gt 0 ] && [ "$1" != "--" ]; do
    while getopts ":hlvcsr:x:X:t:d:o:f:F:" opt; do
      case $opt in
        h)
          $(insthelp verbosehelp $cmd)
          exit ;;
        l)
          $(insthelp license)
          exit ;;
        v)
          $(insthelp version $cmd $ver)
          exit ;;
        c)
          $(insthelp setconfig $cmd)
          exit ;;
        s)
          sample=true ;;
        r)
          outputrenderer=$(insthelp setrenderer $OPTARG) ;;
        X|x)
          $(insthelp sethttp $OPTARG) ;;
        d)
          bridge_domain="$OPTARG" ;;
        t)
          bridge_token="$OPTARG" ;;
        o)
          outputpath=$(insthelp setoutput $OPTARG ${BASH_ARGV[0]})
          if [ "$outputpath" = "ERR" ]; then exit 1; fi ;;
        F|f)
          formopts="$formopts -F $OPTARG" ;;
        \?)
          printf >&2 "Invalid option: \`-$OPTARG\`\r\n"
          $(insthelp help $cmd)
          exit 2 ;;
        :)
          printf >&2 "Missing argument for \`-$OPTARG\`\r\n"
          $(insthelp help $cmd)
          exit 2 ;;
      esac
    done
    shift $((OPTIND-1))
    if [ $# -gt 0 ] && ! [[ "$1" =~ ^- ]]; then
      path="$1"
      shift
      break
    else
      printf >&2 "No API method provided\r\n"
      $(insthelp help $cmd)
      exit 2
    fi
  done
  if [ "$1" == "--" ]; then
    shift
    path=("${path[@]}" "$@")
  fi
fi

# BUILD COMMAND ################################################################
# ##############################################################################
if [ -z "$bridge_domain" ] && [ -z "$bridge_token" ]; then
  $(insthelp readconfig $cmd)
elif [ -z "$bridge_domain" ] || [ -z "$bridge_token" ]; then
  printf >&2 "Both \`-d\` and \`-t\` are requied when not using a config file\r\n"
  $(insthelp help $cmd)
  exit 2
fi
if [ -n "$outputpath" ] && [ -n "$outputrenderer" ]; then
  outputrenderer=""
fi
if [ $path == "admin/data_dumps/download" ]; then
  if [ -z "$outputpath" ]; then
    printf >&2 "Downloading data dumps requires an output path with \`-o\`\r\n"
    $(insthelp help $cmd)
    exit 2
  fi
  if [ ${outputpath: -4} = "json" ]; then
    outputpath="${outputpath/json/}zip"
  fi
  html=$(curl $curlopts -H "Authorization: Basic $bridge_token" "https://$bridge_domain.bridgeapp.com/api/$path")
  url=$(echo "$html" | grep -oE 'href="([^"#]+)"' | sed "s/amp;//g"| cut -f2 -d '"')
  command="curl $curlopts \"$url\" $outputpath"
else
  command="curl $curlopts -H \"Authorization: Basic $bridge_token\" -X $httpmethod \"https://$bridge_domain.bridgeapp.com/api/$path\" $formopts $outputrenderer $outputpath"
fi
if [ "$sample" = true ]; then
  printf >&2 "$command\r\n"
else
  eval $command
fi
